name = "omnidrive-api"
main = "src/index.ts"
compatibility_date = "2025-06-01"
compatibility_flags = [ "nodejs_compat_v2" ]

[triggers]
crons = ["*/30 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "omnidrive"
database_id = "85427fa6-e0ce-4642-92e6-52b638643ef4"

[[kv_namespaces]]
binding = "KV"
id = "f15360e6e6564f0cbec9d5678142abea"

[vars]
FRONTEND_URL = "https://omnidrive.pages.dev"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
